import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/app/components/Header";
import HeaderMobile from "@/app/components/HeaderMobile";
import Script from "next/script";
import Footer from "./components/Footer";

// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "InkForHireBn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="css/bootstrap.min.css" />
        <link rel="stylesheet" href="css/animate.min.css" />
        <link rel="stylesheet" href="css/magnific-popup.css" />
        <link rel="stylesheet" href="fontawesome/css/all.min.css" />
        <link rel="stylesheet" href="font-flaticon/flaticon.css" />
        <link rel="stylesheet" href="css/dripicons.css" />
        <link rel="stylesheet" href="css/slick.css" />
        <link rel="stylesheet" href="css/meanmenu.css" />
        <link rel="stylesheet" href="css/default.css" />
        <link rel="stylesheet" href="css/style.css" />
        <link rel="stylesheet" href="css/responsive.css" />
      </head>
      <body className={inter.className}>
        <Header />
        <HeaderMobile />
        {children}
        <Footer />
        <Script src="js/vendor/modernizr-3.5.0.min.js"></Script>
        <Script src="js/vendor/jquery-3.6.0.min.js"></Script>
        <Script src="js/popper.min.js"></Script>
        <Script src="js/bootstrap.min.js"></Script>
        <Script src="js/slick.min.js"></Script>
        <Script src="js/ajax-form.js"></Script>
        <Script src="js/paroller.js"></Script>
        <Script src="js/wow.min.js"></Script>
        <Script src="js/js_isotope.pkgd.min.js"></Script>
        <Script src="js/imagesloaded.min.js"></Script>
        <Script src="js/parallax.min.js"></Script>
        <Script src="js/jquery.waypoints.min.js"></Script>
        <Script src="js/jquery.counterup.min.js"></Script>
        <Script src="js/jquery.scrollUp.min.js"></Script>
        <Script src="js/jquery.meanmenu.min.js"></Script>
        <Script src="js/parallax-scroll.js"></Script>
        <Script src="js/jquery.magnific-popup.min.js"></Script>
        <Script src="js/element-in-view.js"></Script>
        <Script src="js/main.js"></Script>
      </body>
    </html>
  );
}
